name: Deploy ACR
on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  acrdeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group Proximus_PlayGround \
            --template-file ./defaultacr.bicep
      
